services:
    webprog1-la-php:
        container_name: webprog1-la-php
        image: webprog1-la/php
        build:
          dockerfile: deployment/php.Dockerfile
        volumes:
            - webprog1-la-storage:/var/www/html/public/storage
        networks:
            - webprog1-la-app
        ports:
            - 9000:9000
        depends_on:
            change-vol-ownership:
                condition: service_completed_successfully

    webprog1-la-caddy:
        container_name: webprog1-la-caddy
        image: webprog1-la/caddy
        build:
          dockerfile: deployment/caddy.Dockerfile
        volumes:
            - webprog1-la-storage:/var/www/html/public/storage
        networks:
            - webprog1-la-app
            - captain-overlay-network
        depends_on:
            change-vol-ownership:
                condition: service_completed_successfully

    webprog1-la-sql:
        container_name: webprog1-la-sql
        image: mariadb:latest
        volumes:
            - webprog1-la-db:/var/lib/mysql
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: true
            MYSQL_DATABASE: webprog1-la
            MYSQL_USER: webprog1-la
            MYSQL_PASSWORD: nagyonbiztonsagosjelszo
        networks:
            - webprog1-la-app
        ports:
            - 3306:3306

    change-vol-ownership:
        image: ubuntu
        user: "root"
        group_add:
          - 33
        volumes:
          - webprog1-la-db:/tmp/change-ownership
        command: chown -R 33:33 /tmp/change-ownership

volumes:
    webprog1-la-storage:
    webprog1-la-db:

networks:
    webprog1-la-app:
        name: webprog1-la-app
    captain-overlay-network:
        external: true
