services:
    caddy:
        container_name: caddy
        image: webprog1-la/caddy
        build:
          dockerfile: deployment/caddy.Dockerfile
        volumes:
            - storage:/var/www/html/public/storage
        networks:
            - app
        ports:
            - 8080:80

    php:
        container_name: php
        image: webprog1-la/php
        build:
          dockerfile: deployment/php.Dockerfile
        volumes:
            - storage:/var/www/html/public/storage
        networks:
            - app
        ports:
            - 9000:9000

    sql:
        container_name: sql
        image: mariadb:latest
        volumes:
            - db:/var/lib/mysql
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: true
            MYSQL_DATABASE: webprog1-la
            MYSQL_USER: webprog1-la
            MYSQL_PASSWORD: nagyonbiztonsagosjelszo
        networks:
            - app
        ports:
            - 3306:3306

volumes:
    storage:
    db:

networks:
    app:
        name: app
